### ISSUE TITLE
Explore an issue

### ISSUE THREAD

**Issue by yaroslavNqualisystems** [QualiSystems/cloudshell-cli#101]
2020-03-24 09:24:50,197 [DEBUG]: QS.JuniperLSCP_105.202.Thread-5 expect_session - hardware_expect      
2020-03-24 09:24:50,322 [DEBUG]: QS.JuniperLSCP_105.202.Thread-5 expect_session - hardware_expect      root# 
2020-03-24 09:24:50,539 [DEBUG]: QS.JuniperLSCP_105.202.Thread-5 expect_session - hardware_expect      Command: commit
2020-03-24 09:24:50,794 [DEBUG]: QS.JuniperLSCP_105.202.Thread-5 expect_session - hardware_expect      commit 
2020-03-24 09:24:51,055 [DEBUG]: QS.JuniperLSCP_105.202.Thread-5 expect_session - hardware_expect      
2020-03-24 09:24:51,055 [DEBUG]: QS.JuniperLSCP_105.202.Thread-5 expect_session - hardware_expect      
2020-03-24 09:25:21,059 [DEBUG]: QS.JuniperLSCP_105.202.Thread-5 session_pool_manager - remove_session       Removing session
2020-03-24 09:25:21,060 [DEBUG]: QS.JuniperLSCP_105.202.Thread-5 session_manager_impl - remove_session       SSH session was removed
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             Error occurred
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             Traceback (most recent call last):
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\paramiko\channel.py", line 699, in recv
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 out = self.in_buffer.read(nbytes, self.timeout)
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\paramiko\buffered_pipe.py", line 164, in read
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 raise PipeTimeout()
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             paramiko.buffered_pipe.PipeTimeout
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             During handling of the above exception, another exception occurred:
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             Traceback (most recent call last):
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\cloudshell\cli\session\ssh_session.py", line 137, in _receive
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 byte_data = self._current_channel.recv(self._buffer_size)
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\paramiko\channel.py", line 701, in recv
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 raise socket.timeout()
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             socket.timeout
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             During handling of the above exception, another exception occurred:
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             Traceback (most recent call last):
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\cloudshell\cli\session\expect_session.py", line 152, in _receive_all
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 read_buffer += self._receive(0.1, logger)
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\cloudshell\cli\session\ssh_session.py", line 140, in _receive
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 raise SessionReadTimeout()
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             cloudshell.cli.session.session_exceptions.SessionReadTimeout
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             During handling of the above exception, another exception occurred:
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             Traceback (most recent call last):
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\Windows\TEMP\tmpev0m0ury.zip_env\driver.py", line 141, in Deploy
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 int_list = ls_flow.create_ls(ls_name, int_list)
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\Windows\TEMP\tmpev0m0ury.zip_env\driver_files\flows.py", line 47, in create_ls
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 commit_rollback.commit()
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\cloudshell\networking\juniper\command_actions\commit_rollback_actions.py", line 25, in commit
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 self._cli_service, command_template.COMMIT
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\cloudshell\cli\command_template\command_template_executor.py", line 60, in execute_command
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 **self.optional_kwargs
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\cloudshell\cli\service\cli_service_impl.py", line 143, in send_command
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 **kwargs
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\cloudshell\cli\session\expect_session.py", line 266, in hardware_expect
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 read_buffer = self._receive_all(timeout, logger)
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__               File "C:\ProgramData\QualiSystems\venv\Juniper_LS_Cloud_Provider_2_10\lib\site-packages\cloudshell\cli\session\expect_session.py", line 158, in _receive_all
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__                 self.__class__.__name__, "Socket closed by timeout"
2020-03-24 09:25:21,061 [ERROR]: QS.JuniperLSCP_105.202.Thread-5 logging_session - __exit__             cloudshell.cli.session.session_exceptions.ExpectedSessionException: ('JuniperSSHSession', 'Socket closed by timeout')
[JuniperLSCP_105.202--24-Mar-2020--09-24-22.log](https://github.com/QualiSystems/cloudshell-cli/files/4376474/JuniperLSCP_105.202--24-Mar-2020--09-24-22.log)

**Comment by yaroslavNqualisystems** [comment]
After reboot of the device I cannot reproduce the issue.
After investigation I found that the issue could be fixed by increasing READ_TIMEOUT, which is "timeout" argument of hardware_expect method, but that was not tested.
